### ISSUE TITLE
Do not redistribute JSON for mIRC

### ISSUE THREAD

**Issue by SReject** [dzhan008/sdhacks2016#1]
In [/ucart/scripts/](https://github.com/dzhan008/sdhacks2016/tree/master/ucart/scripts) you include a copy of [JSON for mIRC](https://github.com/SReject/JSON-For-Mirc/tree/v0.2.4) of which stipulates in the [notes section](https://github.com/SReject/JSON-For-Mirc/tree/v0.2.4#notes--) that it is not to be redistributed. Instead remove thefile and link to its [Release Page](https://github.com/SReject/JSON-For-Mirc/releases/tag/v0.2.41-beta) for users of your script(s) to download.

**Comment by dzhan008** [comment]
Okay, it's been removed, thanks for the note.

**Comment by SReject** [comment]
Very much appreciated :)
